#!/bin/bash


 src_dir=/home/ubuntu/scripts
 tgt_dir=/home/ubuntu/backups

 curr_timestamp=$(date "+%Y-%m-%d-%H-%M-%S")
 back_files=$tgt_dir/$curr_timestamp.tgz


 echo "Taking backup on $curr_timestamp"

 tar czf $back_files --absolute-names $src_dir

 echo "Backup complete"
